CREATE TABLE [dbo].[TblUserProfile]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserId] VARCHAR(100) NOT NULL,
	[FirstName] VARCHAR(50)  NULL,
	[LastName] VARCHAR(50)  NULL,
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[dbo].[UserProfile_HISTORY], DATA_CONSISTENCY_CHECK=ON))
